= Сведения об установке на Windows

Настоящее руководство является обобщенной инструкцией по установке системы {dv} 5.5 (системы).

.Руководство приводит следующую информацию:
- Общие требования базовых модулей системы к аппаратному и программному обеспечению.
- Описание установки составляющих систему модулей.
- Общие рекомендации по первоначальной настройке системы.

Полная инструкция по установке и настройке каждого модуля приведена в руководстве администратора соответствующего модуля.

.Инструкция актуальна для следующих версий модулей {dv}:
- {dv} 5. {pl} версии {pl-v}.
- {dv} 5. Служба {ws} версии {worker-v}.
- {dv} 5. {bo} версии {bo-v}.
- {dv} 5. {wf} версии {wf-v}.
- {dv} 5. {dm} версии {dm-v}.
- {dv} 5. {ad} версии {ad-v}.
- {dv} 5. {to} версии {to-v}.
- {dv} 5. {wincl} версии {win-v}.

Система {dv} предназначена для автоматизации управления документами и бизнес-процессами компании.

Система имеет модульную архитектуру, включающую базовые и дополнительные модули.

* Базовые модули {dv} -- образуют систему {dv}, предоставляют ключевые функции и API {dv}.
* Дополнительные модули {dv} -- расширяют существующие функциональные возможности системы {dv}.

// .Модули {dv}
// [plantuml, svg]
// ....
// @startuml
// hide empty description
// '!pragma layout elk
// skinparam rectangleBorderThickness 1
// skinparam defaultTextAlignment center
// skinparam lifelineStrategy solid
// skinparam monochrome true
//
// State "Базовые модули" as base {
//
// State "Платформа" as platform
// State "Базовые\nобъекты" as baseobjects
// State "Управление\nпроцессами" as workflow
// State "Управление\nдокументами" as documentmanagement
// State "Конструктор\nсогласований" as approvaldesigner
// State "{to}" as takeoffice
// State "Windows-клиент" as windowsclient
// State "Служба\nфоновых операций" as workerservice
// }
//
// baseobjects --> platform
// workflow --> platform
// takeoffice --> platform
// windowsclient --> platform
// documentmanagement --> platform
// approvaldesigner --> platform
// workerservice --> platform
//
// platform -[hidden]-> baseobjects
// platform -[hidden]-> workflow
// platform -[hidden]-> takeoffice
// platform -[hidden]-> windowsclient
// platform -[hidden]-> documentmanagement
// platform -[hidden]-> approvaldesigner
// platform -[hidden]-> workerservice
//
// State "Дополнительные модули" as additional {
//
// State "Web-клиент" as webclient
// State "Другие модули" as other
// }
//
// base --> webclient
// base --> other
// base --> additional
//
// @enduml
// ....

.Модули {dv}
[plantuml, svg]
....
@startuml
left to right direction

package "Базовые модули" as base {

["Платформа"] as platform
["Базовые объекты"] as baseobjects
["Управление процессами"] as workflow
["Управление документами"] as documentmanagement
["Конструктор согласований"] as approvaldesigner
["Делопроизводство 4.5"] as takeoffice
["Windows-клиент"] as windowsclient
["Служба фоновых операций"] as workerservice
}

[baseobjects] -- [platform]
[workflow] -- [platform]
[takeoffice] -- [platform]
[windowsclient] -- [platform]
[documentmanagement] -- [platform]
[approvaldesigner] -- [platform]
[workerservice] -- [platform]

package "Дополнительные модули" as additional {

["Web-клиент"] as webclient
["Другие модули"] as other
}

platform -[hidden]-> baseobjects
platform -[hidden]-> workflow
platform -[hidden]-> takeoffice
platform -[hidden]-> windowsclient
platform -[hidden]-> documentmanagement
platform -[hidden]-> approvaldesigner
platform -[hidden]-> workerservice

package "Дополнительные модули" as additional {

["Web-клиент"] as webclient
["Другие модули"] as other
}

base -down-> additional

@enduml
....

.К базовым модулям относятся:
* {pl} -- центральное звено модульной структуры {dv}.
+
.{pl} содержит:
- Службу *{sss}*.
- Компоненты для работы с базами данных.
- Системные карточки _Папки_, _Системные настройки_ и прочие.
- API.
- Базовые сервисы работы с данными (чтение/запись).
- Функции безопасности, поиска и прочие.
+
* Служба {ws} -- обрабатывает задачи, поступившие от других модулей {dv} в фоновом режиме.
* {bo} -- модуль предоставляет:
- Базовые типы карточек: _Задание_, _Группа заданий_, _Документ_.
- Конструкторы для настройки электронного документооборота.
- Справочники, предоставляющие информацию для использования в других карточках.
* {wf} -- содержит службу обработки бизнес-процессов, предоставляет тип карточек _Бизнес-процесс_ и конструктор для настройки БП.
* {dm} -- предоставляет готовое _Приложение_ {dv}, реализующее конкретные прикладные бизнес-сценарии.
* {ad} -- предоставляет типы карточек и бизнес-процессы для организации и выполнения процесса согласования документов.
* {to} -- предоставляет унаследованные от системы {dv} 4.5 типы карточек, оставленные для совместимости решений, которые были созданы в {dv} 4.5.
* {wincl} -- предоставляет клиентские программы _{wincl}_ и _Рабочее место администратора_ (РМА), позволяющие выполнять пользовательские, административные и другие операции в системе {dv}.

.К дополнительным модулям относятся:
* {wc} и другие.

Все модули, за исключением модуля {pl}, являются зависимыми, т.е. для их работы требуются другие модули. Базовые модули могут зависеть от других базовых модулей, дополнительные модули зависят от базовых.

Модули {dv}, как правило, состоят из двух частей:

* Серверной -- для установки на компьютер с сервером {dv}.
* Клиентской -- для установки на пользовательские компьютеры.

Для серверной и клиентской части предоставляются отдельные пакеты установки. Если модуль включает только одну часть (как правило, серверную), предоставляется один пакет установки.

.Назначение пакета установки отражено в его названии (бывают исключения):
* {dv} 5 Platform **server**.msi -- *серверная* часть модуля.
* {dv} 5 Platform **client**.msi -- *клиентская* часть модуля.

== Состав программного обеспечения

Комплект установки системы {dv} состоит из следующих компонентов:
--
.Модуль {pl}:
. `{dv} 5 Platform server.msi` -- серверная часть.
. `{dv} 5 Platform client.msi` -- клиентская часть.
--
--
.Модуль Служба {ws}:
. `{dv} 5 Worker service.msi` -- серверная часть.
. `{dv} 5 Worker service client.msi` -- клиентская часть.
--
.Модуль Консоль управления {dv}:
* `Docsvision 5 Management Console.msi` -- серверная часть.
--
.Модуль {bo}:
. `{dv} 5 BackOffice server.msi` -- серверная часть.
. `{dv} 5 BackOffice client.msi` -- клиентская часть.
--
--
.Модуль {wf}:
. `{dv} 5 Workflow server.msi` -- серверная часть.
. `{dv} 5 Workflow client.msi` -- клиентская часть.
--
--
.Приложение {dm}:
. `{dv} 5 DocumentManagement server.msi` -- серверная часть.
. `{dv} 5 DocumentManagement client.msi` -- клиентская часть.
--
--
.Модуль {ad}:
. `{dv} 5 ApprovalDesigner server.msi` -- серверная часть.
. `{dv} 5 ApprovalDesigner client.msi` -- клиентская часть.
--
--
.Приложение {to}:
. `{dv} 5 TakeOffice server.msi` -- серверная часть.
. `{dv} 5 TakeOffice client.msi` -- клиентская часть.
--
--
.Модуль {wincl}:
. `{dv} 5 WindowsClient server.msi` -- серверная часть.
. `{dv} 5 WindowsClient.msi` -- клиентская часть.
--
