= Общие сведения

Настоящее руководство является обобщенной инструкцией по установке системы {dv} 5.5 (системы).

.Руководство приводит следующую информацию:
- Общие требования базовых модулей системы к аппаратному и программному обеспечению.
- Описание установки составляющих систему модулей.
- Общие рекомендации по первоначальной настройке системы.

Полная инструкция по установке и настройке каждого модуля приведена в руководстве администратора соответствующего модуля.

.Инструкция актуальна для следующих версии модулей {dv}:
- Docsvision 5. Платформа версии {latest-platform}.
- Docsvision 5. Базовые объекты версии {latest-baseobjects}.
- Docsvision 5. Управление процессами версии {latest-workflow}.
- Docsvision 5. Управление документами версии {latest-documentmanagement}.
- Docsvision 5. Конструктор согласований версии {latest-approvaldesigner}.
- Docsvision 5. Делопроизводство 4.5 версии {latest-takeoffice}.
- Docsvision 5. {wincl} версии {latest-windowsclient}.

Система {dv} предназначена для автоматизации управления документами и бизнес-процессами компании.

Система имеет модульную архитектуру, включающую базовые и дополнительные модули.

* Базовые модули {dv} -- образуют систему {dv}, предоставляют ключевые функции и API {dv}.
* Дополнительные модули {dv} -- расширяют существующие функциональные возможности системы {dv}.

.Модули {dv}
[plantuml, svg]
....
@startuml
hide empty description
'!pragma layout elk
skinparam rectangleBorderThickness 1
skinparam defaultTextAlignment center
skinparam lifelineStrategy solid
skinparam monochrome true

State "Базовые модули" as base {

State "Платформа" as platform
State "Базовые объекты" as baseobjects
State "Управление процессами" as workflow
State "Управление документами" as documentmanagement
State "Конструктор согласований" as approvaldesigner
State "Делопроизводство 4.5" as takeoffice
State "Windows-клиент" as windowsclient
}

platform ---> baseobjects
platform --> workflow
platform --> takeoffice
platform ---> windowsclient
platform ----> documentmanagement
platform ----> approvaldesigner

State "Дополнительные модули" as additional {

State "Web-клиент" as webclient
State "Пульс" as pulse
State "Другие модули" as other
}

base --> webclient
base --> pulse
base --> other

@enduml
....

.К базовым модулям относятся:
* {pl} -- центральное звено модульной структуры {dv}.
+
.{pl} содержит:
- Службу *{sss}*.
- Компоненты для работы с базами данных.
- Системные карточки _Папки_, _Системные настройки_ и прочие.
- API.
- Базовые сервисы работы с данными (чтение/запись).
- Функции безопасности, поиска и прочие.
+
* Базовые объекты -- модуль предоставляет:
- Базовые типы карточек: _Задание_, _Группа заданий_, _Документ_.
- Конструкторы для настройки электронного документооборота.
- Справочники, предоставляющие информацию для использования в других карточках.
* Управление процессами -- содержит службу обработки бизнес-процессов, предоставляет тип карточек _Бизнес-процесс_ и конструктор для настройки БП.
* Управление документами -- предоставляет готовое _Приложение_ {dv}, реализующее конкретные прикладные бизнес-сценарии.
* Конструктор согласований -- предоставляет типы карточек и бизнес-процессы для организации и выполнения процесса согласования документов.
* Делопроизводство 4.5 -- предоставляет унаследованные от системы {dv} 4.5 типы карточек, оставленные для совместимости решений, которые были созданы в {dv} 4.5.
* {wincl} -- предоставляет клиентские программы _{wincl}_ и _Рабочее место администратора_ (РМА), позволяющие выполнять пользовательские, административные и другие операции в системе {dv}.

.К дополнительным модулям относятся:
* {wc}.
* Мобильное рабочее место Пульс и другие.

Все модули, за исключением модуля {pl}, являются зависимыми, т.е. для их работы требуются другие модули. Базовые модули могут зависеть от других базовых модулей, дополнительные модули зависят от базовых.

Модули {dv}, как правило, состоят из двух частей:

* Серверной -- для установки на компьютер с сервером {dv}.
* Клиентской -- для установки на пользовательские компьютеры.

Для серверной и клиентской части предоставляются отдельные пакеты установки. Если модуль включает только одну часть (как правило, серверную), предоставляется один пакет установки.

.Назначение пакета установки отражено в его названии (бывают исключения):
* {dv} 5 Platform **server**.msi -- *серверная* часть модуля.
* {dv} 5 Platform **client**.msi -- *клиентская* часть модуля.

== Состав программного обеспечения

Комплект установки системы {dv} состоит из следующих компонентов:
--
.Модуль Платформа:
. `{dv} 5 Platform server.msi` (серверная часть);
. `{dv} 5 Platform client.msi` (клиентская часть).
--
--
.Модуль Базовые объекты:
. `{dv} 5 BackOffice server.msi` (серверная часть);
. `{dv} 5 BackOffice client.msi` (клиентская часть).
--
--
.Модуль Управление процессами:
. `{dv} 5 Workflow server.msi` (серверная часть);
. ` {dv} 5 Workflow client.msi` (клиентская часть).
--
--
.Приложение Управление документами:
. `{dv} 5 DocumentManagement server.msi` (серверная часть);
. `{dv} 5 DocumentManagement client.msi` (клиентская часть).
--
--
.Модуль Конструктор согласований:
. `{dv} 5 ApprovalDesigner server.msi` (серверная часть);
. `{dv} 5 ApprovalDesigner client.msi` (клиентская часть).
--
--
.Приложение Делопроизводство 4.5:
. `{dv} 5 TakeOffice server.msi` (серверная часть);
. `{dv} 5 TakeOffice client.msi` (клиентская часть).
--
--
.Модуль {wincl}:
. `{dv} 5 WindowsClient server.msi` (серверная часть);
. `{dv} 5 WindowsClient.msi` (клиентская часть).
--
