[[ariaid-title1]]
== Программные требования клиента Docsvision

. *Операционная система*:
* Microsoft Windows 10 (Pro, Enterprise);
* Microsoft Windows 8/8.1 (Pro, Enterprise)xref:#fntarg_1[^1^];
* Microsoft Windows 7 SP 1 (Enterprise, Professional, Ultimate);
* или любая ОС, указанная в требованиях серверной части модуля «Docsvision 5. Платформа» (документ [.ph]#[.dfn .term]_Модуль «Docsvision 5. Платформа». Руководство администратора_#, пункт «Необходимое программное обеспечение»).
. *Обязательное программное обеспечение*:
[loweralpha]
.. Microsoft .NET Framework 4.6.1.
.. Microsoft Internet Explorerlink:#fntarg_2[^2^] версии 8, 9, 10 или 11.
. *Дополнительное программное обеспечение*:
* Веб-браузер (для открытия карточек по ссылке):
** +++32-разрядный+++ Microsoft Internet Explorer версии 8link:#fntarg_3[^3^], 9, 10 или 11;
** Google Chrome версий с 19.0 по 72.0 с расширением «Docsvision Windows Client Launcher»;
** или Opera версий 12.0.0 - 23.0.0;
* +++32-разрядные+++ версии приложений Microsoft Office 2007, 2010, 2013 или 2016:
[loweralpha]
.. Microsoft Word (для синхронизации полей карточки).
.. Microsoft Lync 2010 или 2013, или Skype для бизнеса 2016 (для отображения статуса сотрудника в карточке).
+
[NOTE]
====
[.note__title]#Прим.:# Если установленная на компьютере программа «Microsoft Lync 2013» была обновлена на более раннюю версию (например, «Microsoft Lync 2010»), то для корректной работы функции отображения статуса сотрудника нужно удалить из реестра ветки программы «Microsoft Lync 2013»:

** [.ph .filepath]`HKEY_CURRENT_USER\Software\IM Providers\Lync`
** [.ph .filepath]`HKEY_LOCAL_MACHINE\Software\IM Providers\Lync`
====
.. Microsoft Outlook (для отправки карточек по электронной почте).
.. Microsoft Excel (для экспорта представлений).
.. Должен быть установлен компонент "Общие средства Office".
* ABBYY FineReader Scripting Edition 6.0/7.0 – для работы функции распознавания в карточках приложения «Делопроизводство 4.5»;
* ABBYY FineReader Engine 11.0 (32-разрядная версия) – для работы функции распознавания в карточках модуля «Базовые объекты» (в т.ч. для потокового ввода документов и распознавания штрих-кодов). Дополнительная информация приведена в документе [.ph]#[.dfn .term]_Модуль «Docsvision 5. Базовые объекты». Руководство администратора_#, пункт «Настройка ABBYY FineReader Engine».

=== Программное обеспечение, необходимое для использования усиленной квалифицированной или усовершенствованной ЭП

Следующее программное обеспечение должно быть установлено на компьютере с клиентом Docsvision для использования сертификатов УЦ КриптоПро для формирования/проверки усиленной квалифицированной или усовершенствованной ЭП.

. Компоненты криптопровайдера «КриптоПро»:
* КриптоПро CSP версии 3.9/4.0/5.0;
* КриптоПро TSPCOM версии 1.05.1379 / 1.05.1057 / 2.0.12450;
* КриптоПро OCSPCOM версии 1.05.1178 / 1.05.1053 / 2.0.12261;
* КриптоПро CADESCOM 2.0.13292.
. Сертификаты:
* корневой сертификат КриптоПро – должен быть установлен в хранилище «Доверенные корневые центры сертификации» на уровне «Локальный компьютер»;
* сертификат пользователя – должен быть установлен в хранилище «Личное» на уровне «Текущий пользователь».

*Обратите внимание*:

* Для формирования и проверки https://www.cryptopro.ru/products/cades/usage#for_what[усовершенствованной ЭП] должны быть установлены все перечисленные компоненты КриптоПро.
* Для использования функции КриптоПро «Облачный провайдер» требуется «КриптоПро CSP» версии 5.0 или выше. В качестве сервера электронной подписи может выступать КриптоПро DSS.
* Для использования ключей ЭП ГОСТ Р 34.10-2012 требуется «КриптоПро CSP» версии 4.0.
* По вопросам получения компонентов криптопровайдера «КриптоПро» следует обращаться в компанию ООО "КРИПТО-ПРО".

*На уровень выше:* link:../topics/ClientRequirements.adoc[Требования клиента Docsvision]

link:#fnsrc_1[^1^] Работа в ОС Windows 8 поддерживается только в режиме "Рабочего стола". Работа в режиме Metro, в том числе в Metro-Internet Explorer, не поддерживается.

link:#fnsrc_2[^2^] Требуется для работы в РМА.

link:#fnsrc_3[^3^] При работе в браузере Internet Explorer 8 в ОС Windows 7 открытие модального окна из карточки документа может приводить к блокированию основного окна Windows-клиента (до закрытия модального окна).
