[[ariaid-title1]]
== Предоставление прав учетным записям сервисов Docsvision

Серверная часть Docsvision устанавливает в ОС Windows собственные сервисы:

. Сервер Docsvision (включает службу «Docsvision 5.5 Storage Server» и веб-приложение сервера Docsvision, размещенное в IIS) – обеспечивает возможность подключения клиентских приложений.
. Сервис полнотекстового индексирования «Docsvision 5.5 Full-Text Indexing Service» – обеспечивает индексацию данных в БД Docsvision.
. Сервис отложенных операций с файлами «Docsvision 5.5 File Service» – удаляет файлы из хранилища бинарных данных файлов, а также переносит бинарные данные файлов из одного хранилища в другое.
. Сервис управления бизнес-процессами (СУБП) «Docsvision 5.5 Workflow Server» – обрабатывает бизнес-процессы Docsvision.

Администратор должен самостоятельно настроить права учетных записей служб 1-3. Учётные записи можно объединить в группу для удобства назначения прав. Требования учетных записей сервисов Docsvision приведены в документе [.ph]#[.dfn .term]_Модуль «Docsvision 5. Платформа». Руководство администратора_#, Приложение «Требования учетной записи сервера Docsvision».

Рекомендуется назначить учетным записям сервиса полнотекстового индексирования и СУБП персональную лицензию (см. документ [.ph]#[.dfn .term]_Модуль «Docsvision 5. Платформа». Руководство администратора_#, пункт «Назначение и освобождение персональной лицензии»).

*Parent topic:* xref:../topics/InstallandConfigServer.adoc[Установка и настройка сервера Docsvision]
