= Предоставление прав учетным записям сервисов {dv}

Серверная часть {dv} устанавливает в ОС Windows собственные сервисы:

. Сервер {dv} (включает службу "{dv} 5.5 Storage Server" и веб-приложение сервера {dv}, размещенное в IIS) -- обеспечивает возможность подключения клиентских приложений.
. Сервис полнотекстового индексирования "{dv} 5.5 Full-Text Indexing Service" -- обеспечивает индексацию данных в БД {dv}.
. Сервис отложенных операций с файлами "{dv} 5.5 File Service" -- удаляет файлы из хранилища бинарных данных файлов, а также переносит бинарные данные файлов из одного хранилища в другое.
. Сервис управления бизнес-процессами (СУБП) "{dv} 5.5 Workflow Server" -- обрабатывает бизнес-процессы {dv}.

Администратор должен самостоятельно настроить права учетных записей служб 1-3. Учётные записи можно объединить в группу для удобства назначения прав. Требования учетных записей сервисов {dv} приведены в документе _Модуль {pl}. Руководство администратора_, Приложение "Требования учетной записи сервера {dv}".

Рекомендуется назначить учетным записям сервиса полнотекстового индексирования и СУБП персональную лицензию (см. документ _Модуль {pl}. Руководство администратора_, пункт "Назначение и освобождение персональной лицензии").

