= Установка Windows-клиента с сервера {dv}

. Откройте веб-браузер "Internet Explorer" на компьютере пользователя.
+
Если в "Консоли настройки {dv}" для установки клиентской части указана _область установки_ "Для всех пользователей", Internet Explorer нужно запустить с правами администратора компьютера.
. Настройте веб-браузер "Internet Explorer":#
[loweralpha]
.. Добавьте адрес сервера {dv} в *Надежные сайты*.
.. Для зоны надежных сайтов настройте конфигурацию:#
+
* [.ph .menucascade]#*Проверка подлинности пользователя* > *Вход*# в значение "Автоматический вход в сеть с текущим именем пользователя и паролем";
* [.ph .menucascade]#*Элементы ActiveX и модули подключения* > *Использование элементов управления ActiveX, не помеченных как безопасные для использования*# в значение "Включить";
* [.ph .menucascade]#*Элементы ActiveX и модули подключения* > *Разрешить запуск элементов управления ActiveX, которые не использовались ранее, без предупреждения*# в значение "Включить";
* [.ph .menucascade]#*Элементы ActiveX и модули подключения* > *Запуск элементов ActiveX и модулей подключения*# в значение "Включить".
.. В случае использования браузера Internet Explorer версии 11 при запуске Windows-клиента в некоторых операционных системах могут возникнуть проблемы, так как по умолчанию в браузере отключены элементы ActiveX. Чтобы избежать данной ошибки в настройках Internet Explorer включите режим совместимости для адреса сервера {dv}:#
+
[lowerroman]
... Откройте меню [.ph .menucascade]#*Сервис* > *Параметры просмотра в режиме совместимости*#.
... Добавьте адрес сервера {dv} в список сайтов с режимом совместимости.
. В Internet Explorer перейдите на стартовую страницу {dv} вида:#
+
[source,pre,codeblock]
----
http://[имя сервера {dv}]/[имя виртуальной папки {dv}]/StartPage.aspx
----
+
Будут установлены клиентские части модулей "Платформа" и "Windows-клиент" с областью установки, указанной в Консоли настройки {dv}.

[NOTE]
====
[.note__title]#Note:# Если установка не начнется автоматически, щелкните в тексте по ссылке с текстом "здесь".
====
. Дождитесь завершения установки.
+
На рабочий стол и в меню "Пуск" будут добавлены ярлыки для запуска Windows-клиента и РМА.
. Запустите Windows-клиент. При подключении к серверу {dv} будет выполнена установка клиентских частей других базовых модулей, серверные части которых установлены на сервере {dv}.
+
Если в "Консоли настройки {dv}" для установки клиентских компонентов выбрана область установки "Для всех пользователей", Windows-клиент должен быть запущен с правами администратора компьютера.

