= Установка Windows-клиента

Клиентская часть модуля "Windows-клиент" должна быть установлена на компьютеры пользователей {dv}.

"Windows-клиент" может быть установлен двумя способами:

* xref:InstallWinClientFromSite.adoc[с сервера {dv}] -- требуемые компоненты будут загружены с сервера {dv} и установлены автоматически;
* xref:InstallWinClientFromMsi.adoc[из пакета установки (вручную)] -- администратор должен самостоятельно установить клиентские части модулей "Платформа" и "Windows-клиент", остальные базовые модули будут установлены автоматически.

Клиентские компоненты модулей могут быть установлены для текущего пользователя или для всех пользователей компьютера. Область установки выбирается:

* с помощью настройки [.ph .menucascade]#*_{cns}_* > *Настройки сервера* > *Настройка клиентской части* > *Область установки*# -- если компоненты устанавливаются с сервера {dv};
* при установке клиентской части модуля "Платформа" -- если компоненты устанавливаются вручную.

* xref:InstallWinClientFromSite.adoc[Установка Windows-клиента с сервера {dv}].* xref:InstallWinClientFromMsi.adoc[Установка Windows-клиента из установочного пакета].
