[[ariaid-title1]]
== Установка Windows-клиента с сервера Docsvision

. [.ph .cmd]#Откройте веб-браузер «Internet Explorer» на компьютере пользователя.#
+
Если в «Консоли настройки Docsvision» для установки клиентской части указана [.dfn .term]_область установки_ «Для всех пользователей», Internet Explorer нужно запустить с правами администратора компьютера.
. [.ph .cmd]#Настройте веб-браузер «Internet Explorer»:#
[loweralpha]
.. [.ph .cmd]#Добавьте адрес сервера Docsvision в [.keyword .wintitle]*Надежные сайты*.#
.. [.ph .cmd]#Для зоны надежных сайтов настройте конфигурацию:#
+
* [.ph .menucascade]#[.ph .uicontrol]*Проверка подлинности пользователя* > [.ph .uicontrol]*Вход*# в значение «Автоматический вход в сеть с текущим именем пользователя и паролем»;
* [.ph .menucascade]#[.ph .uicontrol]*Элементы ActiveX и модули подключения* > [.ph .uicontrol]*Использование элементов управления ActiveX, не помеченных как безопасные для использования*# в значение «Включить»;
* [.ph .menucascade]#[.ph .uicontrol]*Элементы ActiveX и модули подключения* > [.ph .uicontrol]*Разрешить запуск элементов управления ActiveX, которые не использовались ранее, без предупреждения*# в значение «Включить»;
* [.ph .menucascade]#[.ph .uicontrol]*Элементы ActiveX и модули подключения* > [.ph .uicontrol]*Запуск элементов ActiveX и модулей подключения*# в значение «Включить».
.. [.ph .cmd]#В случае использования браузера Internet Explorer версии 11 при запуске Windows-клиента в некоторых операционных системах могут возникнуть проблемы, так как по умолчанию в браузере отключены элементы ActiveX. Чтобы избежать данной ошибки в настройках Internet Explorer включите режим совместимости для адреса сервера Docsvision:#
+
[lowerroman]
... Откройте меню [.ph .menucascade]#[.ph .uicontrol]*Сервис* > [.ph .uicontrol]*Параметры просмотра в режиме совместимости*#.
... Добавьте адрес сервера Docsvision в список сайтов с режимом совместимости.
. [.ph .cmd]#В Internet Explorer перейдите на стартовую страницу Docsvision вида:#
+
[source,pre,codeblock]
----
http://[имя сервера Docsvision]/[имя виртуальной папки Docsvision]/StartPage.aspx
----
+
Будут установлены клиентские части модулей «Платформа» и «Windows-клиент» с областью установки, указанной в Консоли настройки Docsvision.

[NOTE]
====
[.note__title]#Note:# Если установка не начнется автоматически, щелкните в тексте по ссылке с текстом «здесь».
====
. [.ph .cmd]#Дождитесь завершения установки.#
+
На рабочий стол и в меню «Пуск» будут добавлены ярлыки для запуска Windows-клиента и РМА.
. [.ph .cmd]#Запустите Windows-клиент. При подключении к серверу Docsvision будет выполнена установка клиентских частей других базовых модулей, серверные части которых установлены на сервере Docsvision.#
+
Если в «Консоли настройки Docsvision» для установки клиентских компонентов выбрана область установки «Для всех пользователей», Windows-клиент должен быть запущен с правами администратора компьютера.

*Parent topic:* xref:../topics/InstallWinClient.adoc[Установка Windows-клиента]
