[[ariaid-title1]]
== Установка Windows-клиента

Клиентская часть модуля «Windows-клиент» должна быть установлена на компьютеры пользователей Docsvision.

«Windows-клиент» может быть установлен двумя способами:

* xref:InstallWinClientFromSite.adoc[с сервера Docsvision] – требуемые компоненты будут загружены с сервера Docsvision и установлены автоматически;
* xref:InstallWinClientFromMsi.adoc[из пакета установки (вручную)] – администратор должен самостоятельно установить клиентские части модулей «Платформа» и «Windows-клиент», остальные базовые модули будут установлены автоматически.

Клиентские компоненты модулей могут быть установлены для текущего пользователя или для всех пользователей компьютера. Область установки выбирается:

* с помощью настройки [.ph .menucascade]#[.ph .uicontrol]*Консоль настройки Docsvision* > [.ph .uicontrol]*Настройки сервера* > [.ph .uicontrol]*Настройка клиентской части* > [.ph .uicontrol]*Область установки*# – если компоненты устанавливаются с сервера Docsvision;
* при установке клиентской части модуля «Платформа» – если компоненты устанавливаются вручную.

* *xref:../topics/InstallWinClientFromSite.adoc[Установка Windows-клиента с сервера Docsvision]* +
* *xref:../topics/InstallWinClientFromMsi.adoc[Установка Windows-клиента из установочного пакета]* +

*Parent topic:* xref:../topics/InstallSetupDV.adoc[Установка и настройка системы Docsvision]
