[[ariaid-title1]]
== Установка серверной части других базовых модулей

. [.ph .cmd]#Запустите пакет установки [.ph .filepath]`Docsvision 5 BackOffice server.msi` от имени локального администратора.#
. [.ph .cmd]#Примите предложенные условия лицензионного соглашения и нажмите [.ph .uicontrol]*Далее*.#
. [.ph .cmd]#Чтобы начать установку нажмите [.ph .uicontrol]*Установить*. Дождитесь завершения установки.#
+
В каталог установки будут добавлены файлы со схемами метаданных карточек, пакет установки клиентской части модуля «Базовые объекты».
. [.ph .cmd]#Закройте мастер установки.#

[[InstallServerBackoffice__postreq_a2z_mj2_p3b]]
Аналогичным образом последовательно установите оставшиеся базовые модули:

* [.ph .filepath]`Docsvision 5 Workflow server.msi`,
* [.ph .filepath]`Docsvision 5 DocumentManagement server.msi`,
* [.ph .filepath]`Docsvision 5 ApprovalDesigner server.msi`,
* [.ph .filepath]`Docsvision 5 TakeOffice server.msi`,
* [.ph .filepath]`Docsvision 5 WindowsClient server.msi`.

*Parent topic:* xref:../topics/InstallandConfigServer.adoc[Установка и настройка сервера Docsvision]
