= Действия после первоначальной настройки сервера

== Проверьте настройки сайта {dv}

.Убедитесь в корректности настроек сайта {dv} в настройках IIS:
. Настройте проверку подлинности для приложения {dv}.
. Отключите поддержку 32-разрядных приложений в настройках пула приложений сайта системы {dv}.

Подробная инструкция xref:platform:admin:postConfigure.adoc#x32[приведена] в руководстве для модуля {pl}.

[#disableCache]
== Отключите клиентское кэширование

Рекомендуется отключить кэширование карточек и файлов на компьютере с сервером {dv}, для избежания переполнения клиентского кэша из-за работы СУБП, следствием чего может стать замедление обработки БП.

. Откройте _Редактор реестра_.
. Перейдите к ветке `HKLM\SOFTWARE\{dv}\Platform\5.5\ObjectManager`.
+
Если раздел ObjectManager отсутствует, создайте его самостоятельно.
. Создайте или измените параметр `CacheMode`:#
+
* Тип: `DWORD`
* Значение: `4`
. Повторите шаги 2-3 для ветки `HKLM\SOFTWARE\Wow6432Node\{dv}\Platform\5.5\ObjectManager`.
. Перезапустите службу _{dv} 5.5 Workflow Server_.

[#accountsRights]
== Предоставьте права учетным записям сервисов {dv}

.Серверная часть {dv} устанавливает в ОС Windows собственные сервисы:
Сервер {dv}::
Включает службу {dv} 5.5 Storage Server и веб-приложение сервера {dv}, размещенное в IIS. Сервер {dv} обеспечивает возможность подключения клиентских приложений.

Сервис полнотекстового индексирования::
{dv} 5.5 Full-Text Indexing Service. Сервис полнотекстового индексирования обеспечивает индексацию данных в БД {dv}.

Сервис отложенных операций с файлами:: {dv}
5.5 File Service. Сервис отложенных операций с файлами удаляет файлы из хранилища бинарных данных файлов, а также переносит бинарные данные файлов из одного хранилища в другое.

Сервис управления бизнес-процессами (СУБП)::
{dv} 5.5 Workflow Server. СУБП обрабатывает бизнес-процессы {dv}.

[TIP]
====
Администратор должен самостоятельно настроить права учетных записей указанных выше служб. Учётные записи можно объединить в группу для удобства назначения прав.

Требования учетных записей сервисов {dv} приведены в пункте xref:platfrom:ROOT:requirementsServerAccount.adoc[по ссылке].

Рекомендуется xref:platfrom:admin:AssignmentofVipLicense.adoc[назначить] учетным записям сервиса полнотекстового индексирования и СУБП персональную лицензию.
====
