= Настройка операционной системы

. Отключите контроль учетных записей (UAC) следующим образом:#
[loweralpha]
.. В Редакторе реестра измените значение параметра `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\EnableLUA` на "0".
.. Перезагрузите компьютер.
. Проверьте, включены ли следующие роли и компоненты при помощи _Мастера добавления ролей и компонентов_:#
+
Роли:

* Storage Services / Службы хранилища;
* Default Document / Документ по умолчанию;
* Directory Browsing / Просмотр каталога;
* HTTP Errors / Ошибки HTTP;
* Static Content / Статическое содержимое;
* HTTP Redirection / Перенаправление HTTP;
* HTTP Logging / Ведение журнала HTTP;
* Static Content Compression / Сжатие статического содержимого;
* Request Filtering / Фильтрация запросов;
* Windows Authentication / Проверка подлинности Windows;
* Basic Authentication / Обычная проверка подлинности;
* .NET Extensibility 3.5;
* .NET Extensibility 4.6 (или выше);
* ASP.NET 4.6 (или выше);
* ISAPI Extensions / Расширения ISAPI;
* ISAPI Filters / Фильтры ISAPI;
* IIS Management Console / Консоль управления IIS;
* IIS 6 Metabase Compatibility / Совместимость конфигурации метабазы;
* IIS 6 Management Console / Консоль управления IIS 6.
+
Компоненты:
+
* .NET Framework 3.5;
* .NET Framework 4.6 (или выше);
* ASP.NET 4.6 (или выше);
* HTTP Activation / Активация по HTTP;
* TCP Port Sharing / Совместное использование портов TCP.
+
Подробная инструкция по добавлению ролей и компонентов доступна в интернете:
* https://docs.microsoft.com/ru-ru/windows-server/administration/server-manager/install-or-uninstall-roles-role-services-or-features#see-also[Для Windows Server.]
* https://www.windowscentral.com/how-manage-optional-features-windows-10[Для других версий Windows.]
. Убедитесь, что в списке локальных пользователей и групп Windows существует группа пользователей [.keyword]*IIS_IUSRS* (создается при установке IIS). Если данная группа не существует, создайте её самостоятельно и добавьте в неё пользователей: NETWORK SERVICE, SERVICE, SYSTEM, IUSR.
. IIS по умолчанию исполняется с правами учетной записи [.keyword]*Network Service*. Данная учётная запись должна иметь права на чтение и запись для следующих папок (задаётся через свойства папки):#
+
* системная папка Windows для временных файлов (по умолчанию, папка `Windows\Temp`);
* временная папка IIS `\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\`.
. Для Microsoft Windows Server 2016 и выше: переключите схему управления электропитанием в положение "Высокая производительность".
