= Аппаратные требования сервера {dv}

Требования сервера {dv} к аппаратному обеспечению зависят от общего количества активных пользователей системы {dv}, рассчитываемого по формуле:

[source,pre,codeblock]
----
Общее к-во активных пользователей = К-во активных пользователей + 0.02 * К-во активных БП 
----

где:

* `К-во активных пользователей` -- расчетное максимальное количество активных пользователей, одновременно работающих в {dv};
* `К-во активных БП` -- расчетное максимальное количество БП, одновременно обрабатываемых на данном компьютере.

Если `К-во активных БП` больше 5000, обработка БП должна быть вынесена на дополнительный компьютер (см. документ _Модуль "{dv} 5. Управление процессами". Руководство администратора_, пункт "Настройка кластера СУБП".). В этом случае общее количество активных пользователей будет равно количеству активных пользователей.

В следующей таблице приведены требования в зависимости от общего количества активных пользователей, полученного по приведенной формуле.

.[.table--title-label]##Табл. 1. ##[.title]##Минимальные требования в зависимости от общего количества активных пользователей##
[width="100%",cols="26%,74%",options="header",]
|===
|Общее к-во активных пользователей |Аппаратные требования
|до 50link:#fntarg_1[^1^] a|
Процессор: 2 ГГц или выше, 4 ядра

Оперативная память: от 4 ГБ

Система хранения данных: от 120 ГБ (рекомендуется твердотельный накопитель)

|51-100 a|
Процессор: 2 ГГц или выше, 8 ядер

Оперативная память: от 4 ГБ

Система хранения данных: от 200 ГБ (рекомендуется твердотельный накопитель)

|100-250 a|
Процессор: 2 ГГц или выше, 8 ядер

Оперативная память: от 8 ГБ

Система хранения данных: от 500 ГБ (рекомендуется твердотельный накопитель)

|250-500 a|
Процессор: 2 ГГц или выше, 16 ядер

Оперативная память: от 16 ГБ

Свободное дисковое пространство: от 500 ГБ, твердотельный накопитель

|Более 500 |Необходима кластерная конфигурация серверов {dv}, исходя из примерного расчета: один сервер {dv} на каждые 500 одновременно работающих пользователей.
|===


link:#fnsrc_1[^1^] До 100 пользователей -- приведены требования для совместной с СУБД установки.
